import subprocess
import sys
import os
from flask import Flask, send_from_directory
from threading import Thread

# Point Flask to the 'dist' folder generated by Vite
app = Flask(__name__, static_folder='dist', static_url_path='')

@app.route('/')
def index():
    if os.path.exists(os.path.join(app.static_folder, 'index.html')):
        return send_from_directory(app.static_folder, 'index.html')
    return "Project Origin backend is online."

@app.route('/<path:path>')
def static_proxy(path):
    if os.path.exists(os.path.join(app.static_folder, path)):
        return send_from_directory(app.static_folder, path)
    return send_from_directory(app.static_folder, 'index.html')

def launch_engines():
    # Updated paths to point into the server/ directory
    subprocess.Popen(["python", "-u", "server/runner.py"], stdout=sys.stdout, stderr=sys.stderr)
    subprocess.Popen(["python", "-u", "server/brain.py"], stdout=sys.stdout, stderr=sys.stderr)

if __name__ == '__main__':
    Thread(target=launch_engines).start()
    app.run(host='0.0.0.0', port=10000)
